require:
  - rubocop-rails
  - rubocop-performance
  - rubocop-rspec
  - rubocop-rspec_rails

AllCops:
  TargetRubyVersion: 2.7.8
  NewCops: enable

Style/Documentation:
  Enabled: false
RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

Rails/ResponseParsedBody:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/AnyInstance:
  Enabled: false

Rails/BulkChangeTable:
  Enabled: false

Lint/ConstantDefinitionInBlock:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Rails/UniqueValidationWithoutIndex:
  Enabled: false
